# Generated by Django 3.1.5 on 2021-01-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0002_turisticpoint_atractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='turisticpoint',
            name='comments',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
    ]
