# Generated by Django 3.1.5 on 2021-01-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210128_1044'),
        ('core', '0003_turisticpoint_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='turisticpoint',
            name='reviews',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
