# Generated by Django 3.1.5 on 2021-01-28 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0004_turisticpoint_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='turisticpoint',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
            preserve_default=False,
        ),
    ]
