# Generated by Django 3.1.5 on 2021-01-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210128_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='turisticpoint',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='turistic'),
        ),
    ]
